### ISSUE TITLE
Can't generate tokens

### ISSUE THREAD

**Issue by bbsixzz** [iv-org/youtube-trusted-session-generator#10]
```
[INFO] internally launching GUI (X11 environment)
[INFO] starting Xvfb
[INFO] launching chromium instance
[INFO] launching browser.
[INFO] waiting 10 seconds for the page to fully load.
Traceback (most recent call last):
  File "/usr/app/src/index.py", line 37, in <module>
    loop().run_until_complete(main())
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/app/src/index.py", line 16, in main
    button_play = await tab.select("#movie_player")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/nodriver/core/tab.py", line 243, in select
    raise asyncio.TimeoutError(
TimeoutError: time ran out while waiting for #movie_player
```

**Comment by unixfox** [comment]
please include more details... like are you executing this script on docker or not

**Comment by bbsixzz** [comment]
`sudo docker run quay.io/invidious/youtube-trusted-session-generator`

```
 Static hostname: debian
       Icon name: computer-desktop
         Chassis: desktop 🖥️
      Machine ID: 8cb12864ecf7407195b697ba149b414b
         Boot ID: a8b5167dfdba4ddf8c19fc624ade2f04
Operating System: Debian GNU/Linux 12 (bookworm)  
          Kernel: Linux 6.1.0-25-amd64
    Architecture: x86-64
 Hardware Vendor: ASUS
  Hardware Model: All Series
Firmware Version: 1603
```

**Comment by unixfox** [comment]
How much ram left on the computer? How many cores does the cpu have?

**Comment by bbsixzz** [comment]
`sudo docker run --network=host quay.io/invidious/youtube-trusted-session-generator`

Sorry I thought I posted this, I made it work with `--network=host`

I forgot I had a convoluted VPN setup on the machine.
