### ISSUE TITLE
My returned po_token is actually a base64 encoded error message

### ISSUE THREAD

**Issue by rhavinx** [iv-org/youtube-trusted-session-generator#12]
When I run the container to get the visitor_data and po_token, it returns a token which is 1437 characters long.
Eg: docker run quay.io/invidious/youtube-trusted-session-generator

If I put the token into a file and run base64 against it, it shows the below errors:

Eg: base64 -d base64.txt 

```
*
EBH:Error:Rpc failed due to xhr error. uri: https://jnn-pa.googleapis.com/$rpc/google.internal.waa.v1.Waa/Create, error code: 6, error:  [0]:Error: Rpc failed due to xhr error. uri: https://jnn-pa.googleapis.com/$rpc/google.internal.waa.v1.Waa/Create, error code: 6, error:  [0]
    at new Di (https://www.youtube.com/s/player/26636eff/player_ias.vflset/en_US/base.js:794:46)
    at g.Yi.<anonymous> (https://www.youtube.com/s/player/26636eff/player_ias.vflset/en_US/base.js:950:147)
    at ei (https://www.youtube.com/s/player/26636eff/player_ias.vflset/en_US/base.js:738:208)
    at g.k.dispatchEvent (https://www.youtube.com/s/player/26636eff/player_ias.vflset/en_US/base.js:7880:386)
    at dga (https://www.youtube.com/s/player/26636eff/player_ias.vflset/en_US/base.js:825:34)
    at fga (https://www.youtube.com/s/player/26636eff/player_ias.vflset/en_US/base.js:826:383)
    at g.k.mca (https://www.youtube.com/s/player/26636eff/player_ias.vflset/en_US/base.js:7921:20)
    at g.k.V0 (https://www.youtube.com/s/player/26636eff/player_ias.vflset/en_US/base.js:7920:70)
```

Any ideas?

**Comment by unixfox** [comment]
Maybe your IP is blocked or something is blocking the domain jnn-pa.googleapis.com.

Works fine for me.
