### ISSUE TITLE
Webserver does not boot on Raspberry Pi OS 64bit Lite (no desktop) (Debian Bookworm)

### ISSUE THREAD

**Issue by sagansfault** [iv-org/youtube-trusted-session-generator#18]
What am I missing?
```
pi@raspberrypi:~ $ sudo docker run -p 8080:8080 quay.io/invidious/youtube-trusted-session-generator:webserver
[INFO] internally launching GUI (X11 environment)
[INFO] starting Xvfb
[INFO] launching chromium instance
2024/11/22 21:26:59.153 [extractor] [INFO] update started
Traceback (most recent call last):
  File "/app/potoken-generator.py", line 4, in <module>
    potoken_generator.main.main()
  File "/app/potoken_generator/main.py", line 98, in main
    loop.run_until_complete(main_task)
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/potoken_generator/main.py", line 35, in run
    token = await potoken_extractor.run_once()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/potoken_generator/extractor.py", line 46, in run_once
    await self._update()
  File "/app/potoken_generator/extractor.py", line 91, in _update
    await asyncio.wait_for(self._perform_update(), timeout=600)
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/app/potoken_generator/extractor.py", line 104, in _perform_update
    browser = await nodriver.start(headless=False,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/nodriver/core/util.py", line 74, in start
    return await Browser.create(config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/nodriver/core/browser.py", line 87, in create
    await instance.start()
  File "/usr/local/lib/python3.12/site-packages/nodriver/core/browser.py", line 343, in start
    raise Exception(
Exception:
                ---------------------
                Failed to connect to browser
                ---------------------
                One of the causes could be when you are running as root.
                In that case you need to pass no_sandbox=True

Exception ignored in atexit callback: <function deconstruct_browser at 0x7f8ee88540>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/nodriver/core/util.py", line 124, in deconstruct_browser
    _.stop()
  File "/usr/local/lib/python3.12/site-packages/nodriver/core/browser.py", line 545, in stop
    asyncio.get_event_loop().create_task(self.connection.aclose())
                                         ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'aclose'
```

**Comment by unixfox** [comment]
How much RAM does your device have? Same for the CPU cores?

**Comment by sagansfault** [comment]
Oh you know what that actually might be the problem if it cant even load it into memory.
The machine has 1gb of ram 😆 and a 4 core cpu.

**Comment by unixfox** [comment]
Ha yes maybe I should advertise that you need at the very least 2GB of memory.

It's a full blown browser.

I would advise you to look for other projects on github that can run potoken without a full browser. Not going to share the URL here sorry, we thrive to avoid to sharing things that may interest the curiosity of yt workers.
