### ISSUE TITLE
the websever fails to start 

### ISSUE THREAD

**Issue by achiragaming** [iv-org/youtube-trusted-session-generator#22]
[INFO] internally launching GUI (X11 environment)
[INFO] starting Xvfb
[INFO] launching chromium instance
2024/12/07 18:54:45.655 [extractor] [INFO] update started
Traceback (most recent call last):
  File "/app/potoken-generator.py", line 4, in <module>
    potoken_generator.main.main()
  File "/app/potoken_generator/main.py", line 98, in main
    loop.run_until_complete(main_task)
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/potoken_generator/main.py", line 35, in run
    token = await potoken_extractor.run_once()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/potoken_generator/extractor.py", line 46, in run_once
    await self._update()
  File "/app/potoken_generator/extractor.py", line 91, in _update
    await asyncio.wait_for(self._perform_update(), timeout=600)
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/app/potoken_generator/extractor.py", line 104, in _perform_update
    browser = await nodriver.start(headless=False,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/nodriver/core/util.py", line 74, in start
    return await Browser.create(config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/nodriver/core/browser.py", line 87, in create
    await instance.start()
  File "/usr/local/lib/python3.12/site-packages/nodriver/core/browser.py", line 343, in start
    raise Exception(
Exception: 
                ---------------------
                Failed to connect to browser
                ---------------------
                One of the causes could be when you are running as root.
                In that case you need to pass no_sandbox=True 
                
Exception ignored in atexit callback: <function deconstruct_browser at 0x7f9180998540>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/nodriver/core/util.py", line 124, in deconstruct_browser

    _.stop()
  File "/usr/local/lib/python3.12/site-packages/nodriver/core/browser.py", line 545, in stop
    asyncio.get_event_loop().create_task(self.connection.aclose())
                                         ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'aclose'

**Comment by unixfox** [comment]
https://github.com/iv-org/youtube-trusted-session-generator/issues/3
